### ISSUE TITLE
Geolocation doesn't work on Raspberry Pi tests

### ISSUE THREAD

**Issue by DavSanchez** [DavSanchez/CaptivePortal#1]
Running the node server on the Raspberry Pi and trying to connect to the hotspot with a laptop throws the following error in Firefox: `A Geolocation request can only be fulfilled in a secure context.` The rest of the login process works and I'm granted access to the internet.

Checking `js/script.js` it seems that `navigator.geolocation.watchPosition(...)` is executed (`locationTime` variable remains undefined). When trying the same configuration in local (launching the server from the IDE I am working with) it threw no error at all.

Is this an HTTPS issue? How do I solve it...?

**Comment by pihomeserver** [comment]
No related to a missing HTTPS context as the hotspot only allows HTTP requests ?

**Comment by reigelgallarde** [comment]
more about [geolocation.watchPosition](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition)

> Secure context
This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.


but checking `js/script.js` I'm not sure why you needed it on this project?

**Comment by DavSanchez** [comment]
Hello @reigelgallarde 

At the moment I want to use the location services just to name the sound files uploaded. I plan to do some kind of audio mapping in the future using both the audio file's signal level (RMS) and the location provided by the users of this service.

I too think the location issue has to do with HTTPS, but I had some doubts since Firefox throws no errors when I deploy the project from my laptop and then I access it via `http://localhost:3000/`

**Comment by reigelgallarde** [comment]
Well, I guess, it's better to use google maps API. Is it not an option?
here's a sample code [Geolocation Without SSL connection](https://stackoverflow.com/a/39367531/251986)

**Comment by DavSanchez** [comment]
I'll take a look at that, thank you!
